--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kaxyum/ImagePath
build-by-default: true
branches:
- main
projects:
  ImagePath:
    path: ""
    model: virion
    type: library
...
